### ISSUE TITLE
[NOT A BUG] I'm very interested

### ISSUE THREAD

**Issue by LiskoSlayer63** [TwistedGate/ImmersivePosts#1]
I'm very interested about that mod because I have been waiting for something like this for a while. Tell me if you need some help with coding and stuff, I _might_ be able to help.

**Comment by TwistedGate** [comment]
Thank you! =)
It's been bothering me and since nobody has done it yet i gave it a shot, i mean what could go wrong right? Anyways..

Only thing im struggling with is getting the Extendable Post item to display, and i have like no clue what im doing wrong, it's realy frustrating.
Everything else so far works like a charm.
It's pretty much just the item at this point. =P

So, if you'd like to, you're welcome to give it a shot.

**Comment by LiskoSlayer63** [comment]
That's cool! I'll check tomorrow if I can do something about it. =)

**Comment by TwistedGate** [comment]
Mhm.
Don't worry if you can't figure it out either. lol

**Comment by TwistedGate** [comment]
Actualy, i just figured it out by accident...... this is awkward..

**Comment by LiskoSlayer63** [comment]
No problem mate :D good that you figured it out! I possibly fork this repo and check if I come up with some additions or ideas.
